version: 0.2
env:
  parameter-store:
    DOCKERHUB_USERNAME: "DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "DOCKERHUB_PASSWORD"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Docker Login...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - echo Deploy website
  build:
    commands:
      - rm -rf .git
      - aws s3 cp s3://${config_bucket}/${environment}/.env ./.env
      - yarn install
      - yarn run build
      - aws s3 sync --delete ./build/ s3://${bucket_name}/ 
  post_build:
    commands:
      - echo 'Invalidating distribuition cache'
      - aws cloudfront create-invalidation --distribution-id ${distribuition_id} --paths "/*"

